// Code generated by pg-bindings generator. DO NOT EDIT.

//go:build sql_integration

package postgres

import (
	"context"
	"testing"

	"github.com/jackc/pgx/v4/pgxpool"
	storage "github.com/stackrox/rox/generated/storage"
	"github.com/stackrox/rox/pkg/features"
	"github.com/stackrox/rox/pkg/postgres/pgtest"
	"github.com/stackrox/rox/pkg/sac"
	"github.com/stackrox/rox/pkg/testutils"
	"github.com/stackrox/rox/pkg/testutils/envisolator"
	"github.com/stretchr/testify/suite"
)

type K8srolesStoreSuite struct {
	suite.Suite
	envIsolator *envisolator.EnvIsolator
}

func TestK8srolesStore(t *testing.T) {
	suite.Run(t, new(K8srolesStoreSuite))
}

func (s *K8srolesStoreSuite) SetupTest() {
	s.envIsolator = envisolator.NewEnvIsolator(s.T())
	s.envIsolator.Setenv(features.PostgresDatastore.EnvVar(), "true")

	if !features.PostgresDatastore.Enabled() {
		s.T().Skip("Skip postgres store tests")
		s.T().SkipNow()
	}
}

func (s *K8srolesStoreSuite) TearDownTest() {
	s.envIsolator.RestoreAll()
}

func (s *K8srolesStoreSuite) TestStore() {
	ctx := sac.WithAllAccess(context.Background())

	source := pgtest.GetConnectionString(s.T())
	config, err := pgxpool.ParseConfig(source)
	s.Require().NoError(err)
	pool, err := pgxpool.ConnectConfig(ctx, config)
	s.NoError(err)
	defer pool.Close()

	Destroy(ctx, pool)
	store := New(ctx, pool)

	k8SRole := &storage.K8SRole{}
	s.NoError(testutils.FullInit(k8SRole, testutils.SimpleInitializer(), testutils.JSONFieldsFilter))

	foundK8SRole, exists, err := store.Get(ctx, k8SRole.GetId())
	s.NoError(err)
	s.False(exists)
	s.Nil(foundK8SRole)

	withNoAccess := sac.WithNoAccess(ctx)

	s.NoError(store.Upsert(ctx, k8SRole))
	foundK8SRole, exists, err = store.Get(ctx, k8SRole.GetId())
	s.NoError(err)
	s.True(exists)
	s.Equal(k8SRole, foundK8SRole)

	k8SRoleCount, err := store.Count(ctx)
	s.NoError(err)
	s.Equal(k8SRoleCount, 1)

	k8SRoleCount, err = store.Count(withNoAccess)
	s.NoError(err)
	s.Zero(k8SRoleCount)

	k8SRoleExists, err := store.Exists(ctx, k8SRole.GetId())
	s.NoError(err)
	s.True(k8SRoleExists)
	s.NoError(store.Upsert(ctx, k8SRole))
	s.ErrorIs(store.Upsert(withNoAccess, k8SRole), sac.ErrResourceAccessDenied)

	foundK8SRole, exists, err = store.Get(ctx, k8SRole.GetId())
	s.NoError(err)
	s.True(exists)
	s.Equal(k8SRole, foundK8SRole)

	s.NoError(store.Delete(ctx, k8SRole.GetId()))
	foundK8SRole, exists, err = store.Get(ctx, k8SRole.GetId())
	s.NoError(err)
	s.False(exists)
	s.Nil(foundK8SRole)

	s.ErrorIs(store.Delete(withNoAccess, k8SRole.GetId()), sac.ErrResourceAccessDenied)

	var k8SRoles []*storage.K8SRole
	for i := 0; i < 200; i++ {
		k8SRole := &storage.K8SRole{}
		s.NoError(testutils.FullInit(k8SRole, testutils.UniqueInitializer(), testutils.JSONFieldsFilter))
		k8SRoles = append(k8SRoles, k8SRole)
	}

	s.NoError(store.UpsertMany(ctx, k8SRoles))

	k8SRoleCount, err = store.Count(ctx)
	s.NoError(err)
	s.Equal(k8SRoleCount, 200)
}
